# Generated by Django 2.1.2 on 2018-10-06 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('city_code', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='timedatabase',
            name='city',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='helloworld.TimeZone'),
            preserve_default=False,
        ),
    ]
